In [1]:
import numpy as np
yt = np.genfromtxt("/home/lucas/Desktop/computer_vision/3DCNN/perceptron_ac/yt.txt", delimiter=",").reshape(-1,1)
Xt = np.genfromtxt("/home/lucas/Desktop/computer_vision/3DCNN/perceptron_ac/Xt.txt", delimiter=",")
imgtraining = np.genfromtxt("/home/lucas/Desktop/computer_vision/3DCNN/perceptron_ac/imgtraining.txt", delimiter=",")
imgy = np.genfromtxt("/home/lucas/Desktop/computer_vision/3DCNN/perceptron_ac/imgy.txt", delimiter=",")

In [2]:
imgtraining.shape

(1024, 791)

In [3]:
from perceptronac.coding2d import causal_context

In [23]:
yt2,Xt2 = causal_context(imgtraining, 60)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 59. 56. 60.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 53. 47. 43. 40. 44. 48. 54.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 49. 38. 33. 27. 24. 28. 34. 39. 50.  0.  0.  0.  0.]
 [ 0.  0.  0. 51. 36. 29. 21. 17. 14. 18. 22. 30. 37. 52.  0.  0.  0.]
 [ 0.  0.  0. 45. 31. 19. 11.  9.  6. 10. 12. 20. 32. 46.  0.  0.  0.]
 [ 0.  0. 57. 41. 25. 15.  7.  3.  2.  4.  8. 16. 26. 42. 58.  0.  0.]
 [ 0.  0. 55. 35. 23. 13.  5.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [27]:
Xt2.shape

(787400, 60)

In [8]:
imgtraining.shape

(1024, 791)

In [10]:
( 1024-int(np.ceil(np.sqrt(60))) ) * ( 791 -2* int(np.ceil(np.sqrt(60))))

787400

In [14]:
np.sum(yt != yt2) , np.sum(Xt != Xt2)

(0, 0)

In [6]:
yt.shape,yt2.shape,Xt.shape,Xt2.shape

((787400, 1), (787400, 1), (787400, 60), (787400, 60))