In [9]:
import numpy as np
import datetime

In [10]:
date_format = '%Y-%m-%d'  # "%d/%m/%Y"
def str_to_datetime(s):
    element = datetime.datetime.strptime(s, date_format)
    timestamp = datetime.datetime.timestamp(element)
    return(timestamp)

In [11]:
start = 500
end = 3000
start_gimp_px = 100
end_gimp_px = 835

lbls = ["DVC","DVC_Pro","DCVC","TCM","CANF-VC Lite","CANF-VC","Li et al."]
pts_gimp_px = np.array([200,240,295,365,525,675,425])
years = ['2019-01-01','2020-01-01','2021-01-01','2021-01-01','2022-01-01','2022-01-01','2022-01-01']

In [3]:
kmacperpx = ((pts_gimp_px - start_gimp_px)*(end-start)/(end_gimp_px-start_gimp_px)) + start

In [4]:
kflopsperpx = 2*kmacperpx

In [5]:
kflopsperpx

array([1680.27210884, 1952.38095238, 2326.53061224, 2802.72108844,
       3891.15646259, 4911.56462585, 3210.88435374])

In [6]:
all_systems_compute_flops = kflopsperpx * (1000 * 91701 * 7 * 256 * 256 * 2 * 50)

In [8]:
all_systems_compute_flops

array([7.06857159e+18, 8.21327954e+18, 9.78725297e+18, 1.17904919e+19,
       1.63693237e+19, 2.06619785e+19, 1.35075538e+19])

In [14]:
DAYS_PER_YEAR = 365.2425
HOURS_PER_DAY = 24
MINUTES_PER_HOUR = 60
SECONDS_PER_MINUTE = 60
SECONDS_PER_YEAR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR * HOURS_PER_DAY * DAYS_PER_YEAR

all_systems_datetimes = np.array([str_to_datetime(d) for d in years])
date_intercept_gpu_price_performance = str_to_datetime('2000-01-01')

relative_years = (all_systems_datetimes - date_intercept_gpu_price_performance) / SECONDS_PER_YEAR

tenx_time_gpu_price_performance = 8.17
price_intercept_gpu_price_performance = 7.82 

continuous_price_performance = 10**((1/tenx_time_gpu_price_performance * relative_years) + \
                                    price_intercept_gpu_price_performance)

hardware_replacement_time = 2 * SECONDS_PER_YEAR
hardware_utilization_rate = 0.35

all_systems_training_cost_usd = all_systems_compute_flops / (continuous_price_performance * hardware_replacement_time * hardware_utilization_rate)

In [15]:
all_systems_training_cost_usd

array([22.87839968, 20.05759547, 18.02063977, 21.70907482, 22.74167104,
       28.70539597, 18.76585443])

In [16]:
import matplotlib.pyplot as plt

In [20]:
plt.plot(years, all_systems_training_cost_usd,linestyle="",marker="s")